### ISSUE TITLE
您好，请教一下electron相关的问题

### ISSUE THREAD

**Issue by tangyoulintylgit** [tyust512/xls-electron#19]
I resolved this problem by change the externals options of webpack in vue.config.js.
The document says if there is an error, setting the native dependency as an webpack external.
Here is the document link: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#table-of-contents

Here is the content of vue.config.js, i omit some private config.
Wish this can help someone.

module.exports = {
  configureWebpack: {
    devtool: 'source-map',
  },
  chainWebpack: config => {
    config.resolve.alias
      .set('root', resolve('./'))
      .set('~', resolve('src'))
      .set('@', resolve('src/renderer'))
      .set('@shared', resolve('src/shared'))
      .set('@utils', resolve('src/utils'))
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      customFileProtocol: 'meelauncher://./',
      externals: ['ffi-napi'],
	}
  }
}
因为是electron-vue，怎么找到extrenals这个属性啊？
不好意思，打扰了，以经找到

**Comment by tyust512** [comment]
好的了，随便玩。现在版本升级有点快，我也很久没看electron了
